### ISSUE TITLE
Periodic dimension

### ISSUE THREAD

**Issue by acapet** [gher-ulg/divand.jl#1]
Hello,
Is it possible to specify periodic dimensions ? 

More specifically, I'm thinking of using "Day of the Year" as temporal dimension, ie. to retain seasonal variability but neglect inter annual variability.
To do so we need December 31th (365) to be close a neighbor of Jan 1st (1).

Maybe that is already implemented for longitude ? 

Thanks!

**Comment by Alexander-Barth** [comment]
Yes, this is possible using the keyword argument `moddim`. It is a vector with one element for every dimension. For every periodic dimensions, the corresponding element is the "repeating" period of this dimension. 0 is a special value which means that the dimension is not a periodic dimension.
So for a 3D analysis (longitude, latitude, time) in a global domain with a climatological year, `moddim` would be `[360,0,365]`.
