### ISSUE TITLE
Update emodnet-chemistry.mustache following the attached Sextant xml

### ISSUE THREAD

**Issue by meliezer** [gher-ulg/DIVAnd.jl#14]
The attached example follows the new template.
[sextant_final_example.xml.zip](https://github.com/gher-ulg/DIVAnd.jl/files/2371056/sextant_final_example.xml.zip)
Please note that we always have EMODnet Chemistry as keyword.
Please make sure that the new feature of WMS names (WMSlayername) still functions after modifying the Mustache file.

**Comment by Alexander-Barth** [comment]
@ctroupin do you have everything to make the changes?
Thanks

**Comment by ctroupin** [comment]
Ok so a few commends or doubts concerning the new template. The [file I'm working on](https://github.com/gher-ulg/DIVAnd.jl/blob/NewXMLtemplate2/templates/sextant_final_example_editing.xml) it the branch NewXMLtemplate2:

- [ ]  Some tags appeared multiple times and I'm not sure why, for example `<gmd:pointOfContact>`, and within it we have the same info, for instance <gmd:organisationName>. Do you confirm it is ok?
- [ ] Within one of the pointOfContact I find 
```
<gmd:individualName>
      <gco:CharacterString>John</gco:CharacterString>
</gmd:individualName>
```
what variable will we use for this field (`<name>` is for the organisation).
- [ ] Similarly we have 2 times the email address, one seems to be linked to the organisation, the other to the individual. At the moment I've put `{{ mail }}` for both.

**Comment by meliezer** [comment]
Charles,
It would be easier pointing me to a concrete xml frament. I don't see the multiple tags. Anyway, Erwann should be able to reply. I haven't edited xml files, but worked with Sextant.
In my example there was also the individualName of the originator, which at least for now is always empty for EMODnet Chemistry, so you ignore it. As for SeaDataCloud, you should speak with them.

Also the multiple email addresses, I don't see it.

**Comment by ctroupin** [comment]
ok, let's be more explicit: in the [new template](https://github.com/gher-ulg/DIVAnd.jl/blob/NewXMLtemplate2/templates/sextant_final_example.xml)

lines 20 → 22
```
<gmd:individualName gco:nilReason="missing">
        <gco:CharacterString />
</gmd:individualName>
```

lines 171 → 173
```
<gmd:individualName>
            <gco:CharacterString>John</gco:CharacterString>
</gmd:individualName>
```

And the tag `<gmd:pointOfContact>` appears
1. from lines 110 to 168     then
2. from lines 169 to 192

anyway, I'm contacting now Erwann and let you know.

**Comment by meliezer** [comment]
lines 20 → 22: responsible party, only organisation, no name. It's correct.
lines 171 → 173: in this case it's under gmd:pointOfContact and it has the role of author. For now is always empty for EMODnet Chemistry.

No multiple tags, please note that gmd:role is different: author or originator.

**Comment by ctroupin** [comment]
ok thanks, now it's clearer.

**Comment by Alexander-Barth** [comment]
branch NewXMLtemplate2 is merged.
