### ISSUE TITLE
Interpolations upgrade

### ISSUE THREAD

**Issue by timholy** [gher-ulg/DIVAnd.jl#16]
Interpolations recently released a [new, breaking release](https://github.com/JuliaMath/Interpolations.jl/blob/master/NEWS.md)---see https://github.com/JuliaMath/Interpolations.jl/pull/226 for details.

This package appears to be affected by the bounds-checking change. I recently [placed an upper bound for the package manager](https://github.com/JuliaLang/METADATA.jl/pull/18101) on your behalf, but if you want to continue following the development of Interpolations you may need to make changes. Sorry for any inconvenience.

**Comment by Alexander-Barth** [comment]
Thank you for letting us known. Unfortunately, I cannot not directly upgrade to the lastest version (see the issue on your repository https://github.com/JuliaMath/Interpolations.jl/issues/237).

**Comment by Alexander-Barth** [comment]
We have now upgraded to the latest version of Interpolations. Thanks again for informing us.
