### ISSUE TITLE
Problem with setting up DIVAnd in Julia 1.0.0 on a  linux VM

### ISSUE THREAD

**Issue by croachutas** [gher-ulg/DIVAnd.jl#19]
I've previously made use of the Matlab version of DIVAnd, but after running into memory management issues I've started moving over to Julia. I've installed DIVAnd in Julia 1.0.0 successfully on my Windows 10 laptop to do some test runs, but all my data is on a linux VM (and I expect the full global run will need the 50GB of RAM I've got on teh VM rather than teh 8ish I've got on my laptop).

Anyway, following the install procedure described in the README.me I can successfully pull the source code off github. However, midway through running either using DIVAnd or Pkg.test("DIVAnd") Julia spits out the following error:
```
ERROR: LoadError: LoadError: UndefVarError: ind2sub not defined
Stacktrace:
 [1] getproperty(::Module, ::Symbol) at ./sysimg.jl:13
 [2] top-level scope at none:0
 [3] include at ./boot.jl:317 [inlined]
 [4] include_relative(::Module, ::String) at ./loading.jl:1038
 [5] include at ./sysimg.jl:29 [inlined]
 [6] include(::String) at /home/ubuntu/.julia/dev/DIVAnd/src/DIVAnd.jl:3
 [7] top-level scope at none:0
 [8] include at ./boot.jl:317 [inlined]
 [9] include_relative(::Module, ::String) at ./loading.jl:1038
 [10] include(::Module, ::String) at ./sysimg.jl:29
 [11] top-level scope at none:2
 [12] eval at ./boot.jl:319 [inlined]
 [13] eval(::Expr) at ./client.jl:389
 [14] top-level scope at ./none:3
in expression starting at /home/ubuntu/.julia/dev/DIVAnd/src/statevector.jl:187
in expression starting at /home/ubuntu/.julia/dev/DIVAnd/src/DIVAnd.jl:27
ERROR: Failed to precompile DIVAnd [efc8151c-67de-5a8f-9a35-d8f54746ae9d] to /home/ubuntu/.julia/compiled/v1.0/DIVAnd/AaVxY.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] macro expansion at ./logging.jl:313 [inlined]
 [3] compilecache(::Base.PkgId, ::String) at ./loading.jl:1184
 [4] _require(::Base.PkgId) at ./logging.jl:311
 [5] require(::Base.PkgId) at ./loading.jl:852
 [6] macro expansion at ./logging.jl:311 [inlined]
 [7] require(::Module, ::Symbol) at ./loading.jl:834
```

Now, if I was getting the same error on my windows install I'd just assume it meant some part of the code hadn't been updated now Julia 1.0.0 has dropped support for ind2sub and similar... But it works on my windows install of, supposedly, the same version of Julia, which makes me think there's something else going on.

Note: I installed Julia 1.0.0 to my Windows laptop using the self extracting .exe version, while on the linux VM I compiled Julia 1.0.0 from the source-code.

**Comment by ctroupin** [comment]
`ind2sub` is not in Julia 1.0.0 anymore, it has been deprecated since version 0.7.0, see 
* https://docs.julialang.org/en/v0.7/NEWS/#Deprecated-or-removed-1
* https://github.com/JuliaLang/julia/pull/24715

but in `DIVAnd` the function `ind2sub` is defined [here](https://github.com/gher-ulg/DIVAnd.jl/blob/master/src/statevector.jl#L211), so it's strange it is not found.

What to you type VERSION in a Julia session in the VM? 

Would that be an option to also test the VM with the generic linux binaries provided at https://julialang.org/downloads/?

**Comment by Alexander-Barth** [comment]
This is quite strange, as we do not see this error on travis CI or on our Linux machines.
Can you give us the output of this?

```bash
cd ~/.julia/dev/DIVAnd
git log --oneline
```

Did you run julia's internal test suite ? (`make testall` I think)

**Comment by croachutas** [comment]
Thanks.

Okay, unistalled Julia, cleaned up stray folders it had cloned DIVAnd to, reinstalled everything and cloned and built DIVAnd anew.

It's working now. I presume something went wrong when I first cloned it resulting in a corrupted version, and when I tried to re-clone and build it julia kept on finding the old dud copy.
