### ISSUE TITLE
Wrong name and description in gmd:MD_DigitalTransferOptions

### ISSUE THREAD

**Issue by meliezer** [gher-ulg/DIVAnd.jl#26]
Hello,
All three name and description in gmd:MD_DigitalTransferOptions don't follow the emodnet-chemistry.mustache.

**Comment by Alexander-Barth** [comment]
What values are you seeing in  gmd:MD_DigitalTransferOptions and which values are you expecting?

**Comment by meliezer** [comment]
I'm sorry. I'm attaching the test xml file. I expect to see the related xml
in emodnet-chemistry.mustache.

Il giorno gio 22 nov 2018 alle ore 11:48 Alexander Barth <
notifications@github.com> ha scritto:

**Comment by meliezer** [comment]
In addition, gmd:metadataStandardName is wrong. I see no match between the xml and emodnet-chemistry.mustache.

**Comment by meliezer** [comment]
Good news: For some reason I couldn't update the package, not even after rm end then clone.
Once I've removed the local directory DIVAnd/9uy0 from the hidden Julia directory under home, all is fine.

**Comment by meliezer** [comment]
It was under /home/menashe/.julia/packages which belongs to my Julia 1.0,
which I don't use anymore since it's not supported by you.
I may still have it installed somewhere.
Anyway, all what I've reported relates to version 0.6.4 which has its
packages under /home/menashe/.julia/v0.6
Do you recommend me to removed /home/menashe/.julia/packages (of 1.0) for
not having similar problems?

Thank you!
Menashè



Il giorno gio 22 nov 2018 alle ore 15:27 Alexander Barth <
notifications@github.com> ha scritto:

**Comment by Alexander-Barth** [comment]
In fact, we do now support julia 1.0. You can keep the folder home/menashe/.julia/packages, but just in case when you want to use julia 1.0 remember to update it before as updating a package in julia 0.6 does not update the package in julia 1.0. 
Regards!
