### ISSUE TITLE
elevation_max is -0.0 using diva2xml

### ISSUE THREAD

**Issue by meliezer** [gher-ulg/DIVAnd.jl#28]
Hello,
I see under 
```
<gmd:verticalElement>:
   <gmd:maximumValue>
   <gco:Real>-0.0</gco:Real>
</gmd:maximumValue>
```
while it should be 0.0

**Comment by Alexander-Barth** [comment]
Where do you expect a problem from this? Julia does not distinguish between them, and mathematically they are the same.

```
julia> 0.0 == -0.0
true
```

**Comment by meliezer** [comment]
It seems strange for the Sextant record reader, but since you think
otherwise, I'll check later with others and let you know.


Il giorno gio 22 nov 2018 alle ore 13:08 Alexander Barth <
notifications@github.com> ha scritto:

**Comment by Alexander-Barth** [comment]
This should be solved in commit https://github.com/gher-ulg/DIVAnd.jl/commit/7cbc96c92cbe3d1c4abba683c174a9192ab6247b , now available in the master branch.

**Comment by meliezer** [comment]
Perfect!
