### ISSUE TITLE
Diva2xml: only one WMS and one OPeNDAP URLs

### ISSUE THREAD

**Issue by meliezer** [gher-ulg/DIVAnd.jl#29]
I've created XML for the 4 NetCDF files of Baltic silicate. I would expect 4 OPeNDAP URLs and around 44 WMS URLs, but there is only one of each. The should start from the winter using 'OPeNDAP (winter)' both as name and as description.

**Comment by meliezer** [comment]
As for the WMS URLs, please wait for a possibile new definition.

**Comment by meliezer** [comment]
Please go ahead as explained in the email. No need to wait.

**Comment by Alexander-Barth** [comment]
I am working on this right now...

**Comment by meliezer** [comment]
Done, thank you!
