### ISSUE TITLE
divand test fail

### ISSUE THREAD

**Issue by GeoTuxMan** [gher-ulg/divand.jl#3]
Hi,

I just install Diva 4.7.1 and Julia on  a workstation with Windows 8 (64 bit); when I try to test divand:
Pkg.test("divand")

one test did't pass.

See the file attached.
Looking forward for some tips.

Cheers !
George
[Julia_Error_Install.txt](https://github.com/gher-ulg/divand.jl/files/1614998/Julia_Error_Install.txt)

**Comment by Alexander-Barth** [comment]
I think that this has do to with the fact that the test in question use a random matrix. I changed this now. Can you update your version of divand:
```julia
Pkg.update("divand")
```
And then re-run the tests again?

```julia
Pkg.test("divand")
```
 Thank you for your feed-back!

**Comment by GeoTuxMan** [comment]
Yeah...many thanks...now all tests have passed.
So, I continued with : 
1) Pkg.add("PyCall") 
2) install pyjulia, numpy, matplotlib
3) download divand.py
4) set a system variable PYTHONPATH=C:\Python27\;C:\Python27\Lib;C:\Python27\DLLs;C:\divand.py\divand\divand.py
5) run python divand_argo.py
  I got the error: No module named divand
