### ISSUE TITLE
Divadoxml: wrong thumbnail link

### ISSUE THREAD

**Issue by meliezer** [gher-ulg/DIVAnd.jl#32]
Hello,
The decoded URL from gmd:MD_BrowseGraphic of the test file you've sent me results in HTTP 502:
http://ec.oceanbrowser.net/emodnet/Python/web/wms:?service=WMS&request=GetMap&version=1.3.0&crs=CRS%3A84&bbox=9.4%2C53.0%2C30.9%2C65.9&decorated=true&format=image%2Fpng&layers=Baltic%20Sea%2FWinter%20%28December-February%29%20-%206-years%20running%20averages%2FWater_body_silicate.4Danl.nc%2AWater_body_silicate_L1&styles=vmin%3A8.960959%2Bvmax%3A314.72522&transparent=true&height=500&width=800

**Comment by Alexander-Barth** [comment]
Unfortunately, the fix here has not been released yet:
https://github.com/JuliaWeb/HTTP.jl/issues/323

I will implemented a work-around.

**Comment by meliezer** [comment]
In the new XML you've sent me I see (after decoding): http://ec.oceanbrowser.net/emodnet/Python/web/wms?service=WMS&request=GetMap&version=1.3.0&crs=CRS:84&bbox=11.5,39.0,20.0,46.0&decorated=true&format=image/png&layers=Black%20Sea//tmp/Water_body_Salinity_Adriatic.4Danl.nc*Salinity_L1&styles=vmin:38.13879+vmax:39.208515&transparent=true&height=500&width=800
which results in:
<![CDATA[ Operation not supported ]]>

**Comment by ctroupin** [comment]
I'm not sure of that, but I think it's because the example XML that we've provided does not correspond to a netCDF file available on OceanBrowser, so it cannot generate the thumbnail.

**Comment by meliezer** [comment]
You are right! So I'll wait to have a working environment or a new file.




Il giorno mer 12 dic 2018 alle ore 17:44 Charles Troupin <
notifications@github.com> ha scritto:

**Comment by ctroupin** [comment]
I guess I can create a new XML from an existing netCDF on OceanBrowser, if that helps.

**Comment by meliezer** [comment]
Remember ti mirror the files structure.


Il giorno mer 12 dic 2018, 21:42 Charles Troupin <notifications@github.com>
ha scritto:

**Comment by meliezer** [comment]
I confirm it's fixed.
