### ISSUE TITLE
Divadoxml: Wrong WMS layers for Observations

### ISSUE THREAD

**Issue by meliezer** [gher-ulg/DIVAnd.jl#33]
An example from the resulted XML file, after importing to Sextant:
http://ec.oceanbrowser.net/emodnet/?server=http://ec.oceanbrowser.net/emodnet/Python/web/wms?SERVICE=WMS&amp;REQUEST=GetCapabilities&amp;VERSION=1.3.0&layers=Baltic%20Sea/Winter%20(December-February)%20-%206-years%20running%20averages/Water_body_silicate.4Danl.nc*obsid

**Comment by Alexander-Barth** [comment]
To better understand the issue, does the other field with the silicate analysis work? 
These links are created internally by sextant.

**Comment by meliezer** [comment]
Right, only the WMS layers for Observations are wrong, and the link I've cited is from the XML file after importing to Sextant. It's not clear what is the cause:
`<gmd:onLine><gmd:CI_OnlineResource><gmd:linkage><gmd:URL>http://ec.oceanbrowser.net/emodnet/Python/web/wms?SERVICE=WMS&amp;REQUEST=GetCapabilities&amp;VERSION=1.3.0</gmd:URL></gmd:linkage><gmd:protocol><gco:CharacterString>OGC:WMS</gco:CharacterString></gmd:protocol><gmd:name><gco:CharacterString>Baltic Sea/Winter (December-February) - 6-years running averages/Water_body_silicate.4Danl.nc*Water_body_silicate_L1</gco:CharacterString></gmd:name><gmd:description><gco:CharacterString>WMS layer for Water_body_silicate masked using relative error threshold 0.3 (winter)</gco:CharacterString></gmd:description><gmd:function><gmd:CI_OnLineFunctionCode codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/codelist/ML_gmxCodelists.xml#CI_OnLineFunctionCode" codeListValue=""/></gmd:function></gmd:CI_OnlineResource></gmd:onLine><gmd:onLine><gmd:CI_OnlineResource><gmd:linkage><gmd:URL>http://ec.oceanbrowser.net/emodnet/Python/web/wms?SERVICE=WMS&amp;REQUEST=GetCapabilities&amp;VERSION=1.3.0</gmd:URL></gmd:linkage><gmd:protocol><gco:CharacterString>OGC:WMS</gco:CharacterString></gmd:protocol><gmd:name><gco:CharacterString>Baltic Sea/Winter (December-February) - 6-years running averages/Water_body_silicate.4Danl.nc*obsid</gco:CharacterString></gmd:name><gmd:description><gco:CharacterString>WMS layer for Observations (winter)</gco:CharacterString></gmd:description><gmd:function><gmd:CI_OnLineFunctionCode codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/codelist/ML_gmxCodelists.xml#CI_OnLineFunctionCode" codeListValue=""/></gmd:function></gmd:CI_OnlineResource></gmd:onLine>`

**Comment by Alexander-Barth** [comment]
To give some context, it is the first time that we also show the Observation location in Sextant. I will ask Erwann if he sees what could be the issue.

**Comment by Alexander-Barth** [comment]
The CINECA firewall (see my mail message from this morning) issue is even more sever that I thought as the web-server cannot event connect to itself which prevents me from debugging this issue in more details.

**Comment by meliezer** [comment]
Now that the connection problem is resolved, all is fine.
