### ISSUE TITLE
Divadoxml: missing email address per originator

### ISSUE THREAD

**Issue by meliezer** [gher-ulg/DIVAnd.jl#35]
Hello,
Even though the email address is no longer displayed in the Sextant HTML, it should exists in the XML.
I quote Erwann:
> Concerning the email address, even if we do not display them in the sheet, it is reaaly important to keep these information in the xml because it is a INSPIRE requirement to have at minimum, for each point of contact, an email and an organization.

**Comment by Alexander-Barth** [comment]
Is really missing? In an example file I see the XML fragment:

```
              <gmd:address>
                <gmd:CI_Address>
                  <gmd:deliveryPoint xmlns:xslt="http://xml.apache.org/xslt">
                    <gco:CharacterString>Seestrasse 15</gco:CharacterString>
                  </gmd:deliveryPoint>
                  <gmd:city xmlns:xslt="http://xml.apache.org/xslt">
                    <gco:CharacterString>Rostock</gco:CharacterString>
                  </gmd:city>
                  <gmd:administrativeArea xmlns:xslt="http://xml.apache.org/xslt" gco:nilReason="missing">
                    <gco:CharacterString />
                  </gmd:administrativeArea>
                  <gmd:postalCode xmlns:xslt="http://xml.apache.org/xslt">
                    <gco:CharacterString>18119</gco:CharacterString>
                  </gmd:postalCode>
                  <gmd:country xmlns:xslt="http://xml.apache.org/xslt">
                    <gco:CharacterString>Germany</gco:CharacterString>
                  </gmd:country>
                  <gmd:electronicMailAddress>
                    <gco:CharacterString>postmaster@io-warnemuende.de</gco:CharacterString>
                  </gmd:electronicMailAddress>
                </gmd:CI_Address>
              </gmd:address>
``` 
Can you give me an example where an Email address is missing (and it is not missing in the EDMO database) ?

**Comment by meliezer** [comment]
You are right!
However, I may need to open a different issue, but first I want to know if it's actually an EDMO problem.
e.g. EDMO 729
1. missing email, but:
<gmd:electronicMailAddress>
instead of 
<gmd:electronicMailAddress gco:nilReason="missing">
2. Not missing phone, but:
<gmd:voice gco:nilReason="missing">
       <gco:CharacterString>+45 8715000</gco:CharacterString>
</gmd:voice>

Anyway, this new issue is really in low priority.

**Comment by meliezer** [comment]
I also see that these problems are missing from the xml file exported from Sextant after importing your xml.
