### ISSUE TITLE
Divadoxml: change season for thumbnail

### ISSUE THREAD

**Issue by meliezer** [gher-ulg/DIVAnd.jl#40]
Winter is used for the thumbnail URL, but usually it has less data. Would you please change it to Spring or Summer? You can choose based on your experience.

**Comment by Alexander-Barth** [comment]
This is now possible with the additional argument `previewindex` to `divadoxml`. The default value is one (i.e. winter), but you can set to e.g. 2 for spring.

**Comment by meliezer** [comment]
Great, thank you!
