### ISSUE TITLE
DIVAnd.fit issue

### ISSUE THREAD

**Issue by fricour** [gher-ulg/DIVAnd.jl#44]
Hello,

I am trying to find the optimal correlation length for a 2D layer, i.e. a layer of the global ocean, let's say at 100m. I was doing some tests and used DIVAnd.fit_isotropic taking into account the following inputs: x (the coordinates), v the value, distbin and mincount (I read the doc but distbin is missing in the description of the function). Now, I am trying to use DIVAnd.fit, which takes the same arguments in input but I keep encounting this error:

UndefVarError: Opt not defined

Stacktrace:
 [1] #fit#506(::Array{Int64,1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Float64, ::Array{Float64,1}, ::Float64, ::Float64, ::Float64, ::Int64, ::Int64, ::getfield(DIVAnd, Symbol("##508#515")), ::getfield(DIVAnd, Symbol("##509#516")), ::typeof(DIVAnd.fit), ::Tuple{Array{Float64,1},Array{Float64,1}}, ::Array{Float64,1}, ::Array{Int64,1}, ::Int64) at /home/flo/.julia/packages/DIVAnd/azb67/src/fit.jl:474
 [2] fit(::Tuple{Array{Float64,1},Array{Float64,1}}, ::Array{Float64,1}, ::Array{Int64,1}, ::Int64) at /home/flo/.julia/packages/DIVAnd/azb67/src/fit.jl:422
 [3] top-level scope at In[198]:1

I looked at the source code at the line 474 but cannot do anything about it. Do you have any ideas on how to make it work?

Thank you!

**Comment by ctroupin** [comment]
hello, can you provide us with a minimum working example (i.e. subset of the dataset) and the commands you ran to get this issue?
Otherwise the error messages don't help too much in this case, I'm afraid.

**Comment by fricour** [comment]
Data : [divand_github_issue.txt](https://github.com/gher-ulg/DIVAnd.jl/files/3314561/divand_github_issue.txt)

Hello,

The subset is given in the attached txt file above (columns order : lon, lat, sigma (density) and depth).
If we create a matrix `m` with lon, lat, sigma and depth (size of 64800x4):

This command works : `~, len, ~,~,~ = DIVAnd.fit_isotropic((m[:,1],m[:,2]), m[:,3], collect(0:1:20), 100)`
but this one does not `~, len, ~,~,~ = DIVAnd.fit((m[:,1],m[:,2]), m[:,3], collect(0:1:20), 100)`

I also added the depth field in the text file because I was testing the function fithorzlen, which gives me an error as well. I used the following command : 

`lenz, dbinfo = DIVAnd.fithorzlen((m[:,1],m[:,2],m[:,4]), m[:,3], [50.60,70])` where I used a variable `z` equal to `[50.,60,70]` (´z´ is not defined in the documentation, I had to go in one of the examples to see what it was related to anf got the following result:

> ┌ Warning: Be patient big data set: 64800
└ @ DIVAnd /home/flo/.julia/packages/DIVAnd/azb67/src/fit.jl:675
┌ Warning: Too few data. Will use guesses (np = 0, RLz = 1.811113649598692, )
└ @ DIVAnd /home/flo/.julia/packages/DIVAnd/azb67/src/fit.jl:894
┌ Info: Data points at z=50.6: 64800, horz. correlation length: 1.811113649598692
└ @ DIVAnd /home/flo/.julia/packages/DIVAnd/azb67/src/fit.jl:1061
┌ Warning: Be patient big data set: 64800
└ @ DIVAnd /home/flo/.julia/packages/DIVAnd/azb67/src/fit.jl:675
┌ Warning: Too few data. Will use guesses (np = 0, RLz = 1.811113649598692, )
└ @ DIVAnd /home/flo/.julia/packages/DIVAnd/azb67/src/fit.jl:894
┌ Info: Data points at z=70.0: 64800, horz. correlation length: 1.811113649598692
└ @ DIVAnd /home/flo/.julia/packages/DIVAnd/azb67/src/fit.jl:1061

All elements in A are equal to the fill-value.  No filling is possible

Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] DIVAnd_fill!(::Array{Float64,1}, ::Float64) at /home/flo/.julia/packages/DIVAnd/azb67/src/DIVAnd_fill!.jl:84
 [3] #fithorzlen#522(::Float64, ::Float64, ::Float64, ::Float64, ::Function, ::Function, ::getfield(DIVAnd, Symbol("##526#533")), ::Int64, ::Bool, ::Array{Float64,1}, ::typeof(fithorzlen), ::Tuple{Array{Float64,1},Array{Float64,1},Array{Float64,1}}, ::Array{Float64,1}, ::Array{Float64,1}) at /home/flo/.julia/packages/DIVAnd/azb67/src/fit.jl:1065
 [4] fithorzlen(::Tuple{Array{Float64,1},Array{Float64,1},Array{Float64,1}}, ::Array{Float64,1}, ::Array{Float64,1}) at /home/flo/.julia/packages/DIVAnd/azb67/src/fit.jl:1022
 [5] top-level scope at In[313]:1

Maybe I am using it all wrong but I am not sure ! I also fixed some bugs by updating julia from a version 1.0.x to 1.1.1 (e.g. DIVAndrun was not working on my laptop with julia version 1.0.x)

For information, all tests are OK when using Pkg.test("DIVAnd")

Thanks for your help!

**Comment by ctroupin** [comment]
Thanks for the files, that really help to try and reproduce the issue.

It seems the package `NLopt` is missing from the requirement list. While we are fixing this, you can add install `NLopt` if it is not yet there, then add the following line in `DIVAnd.jl` 
```julia
using NLopt
```
then re-run the code with `DIVAnd.fit(...)`. With your data I get len = [0.5, 0.5]

**Comment by fricour** [comment]
Hello,

I installed NLopt and I did Pkg.update() in any case. I've rerun everything, have restarted the kernel, I still have the same issue.

**Comment by ctroupin** [comment]
And did you add `using NLopt` in `DIVAnd.jl`?

**Comment by fricour** [comment]
Yes of course !

**Comment by Alexander-Barth** [comment]
The functionality of DIVAnd.fit and DIVAnd.fit_isotropic have been replaced by other functions. In future version DIVAnd.fit and DIVAnd.fit_isotropic will be removed. Can you use the other function (DIVAnd.fithorzlen and DIVAnd.fitvertlen ) instead?

**Comment by fricour** [comment]
I did. I also got an issue (see also previous messages).

The error I get with DIVAnd.fithorzlen is, when using `lenz, dbinfo = DIVAnd.fithorzlen((m[:,1],m[:,2],m[:,4]), m[:,3], [50.,60,70])`

> ┌ Warning: Be patient big data set: 64800
└ @ DIVAnd /home/flo/.julia/packages/DIVAnd/lgTG2/src/fit.jl:675
┌ Warning: Too few data. Will use guesses (np = 0, RLz = 1.811113649598692, )
└ @ DIVAnd /home/flo/.julia/packages/DIVAnd/lgTG2/src/fit.jl:894
┌ Info: Data points at z=50.0: 64800, horz. correlation length: 1.811113649598692
└ @ DIVAnd /home/flo/.julia/packages/DIVAnd/lgTG2/src/fit.jl:1061
┌ Warning: Be patient big data set: 64800
└ @ DIVAnd /home/flo/.julia/packages/DIVAnd/lgTG2/src/fit.jl:675
┌ Warning: Too few data. Will use guesses (np = 0, RLz = 1.811113649598692, )
└ @ DIVAnd /home/flo/.julia/packages/DIVAnd/lgTG2/src/fit.jl:894
┌ Info: Data points at z=60.0: 64800, horz. correlation length: 1.811113649598692
└ @ DIVAnd /home/flo/.julia/packages/DIVAnd/lgTG2/src/fit.jl:1061
┌ Warning: Be patient big data set: 64800
└ @ DIVAnd /home/flo/.julia/packages/DIVAnd/lgTG2/src/fit.jl:675
┌ Warning: Too few data. Will use guesses (np = 0, RLz = 1.811113649598692, )
└ @ DIVAnd /home/flo/.julia/packages/DIVAnd/lgTG2/src/fit.jl:894
┌ Info: Data points at z=70.0: 64800, horz. correlation length: 1.811113649598692
└ @ DIVAnd /home/flo/.julia/packages/DIVAnd/lgTG2/src/fit.jl:1061

All elements in A are equal to the fill-value.  No filling is possible

Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] DIVAnd_fill!(::Array{Float64,1}, ::Float64) at /home/flo/.julia/packages/DIVAnd/lgTG2/src/DIVAnd_fill!.jl:84
 [3] #fithorzlen#522(::Float64, ::Float64, ::Float64, ::Float64, ::Function, ::Function, ::getfield(DIVAnd, Symbol("##526#533")), ::Int64, ::Bool, ::Array{Float64,1}, ::typeof(fithorzlen), ::Tuple{Array{Float64,1},Array{Float64,1},Array{Float64,1}}, ::Array{Float64,1}, ::Array{Float64,1}) at /home/flo/.julia/packages/DIVAnd/lgTG2/src/fit.jl:1065
 [4] fithorzlen(::Tuple{Array{Float64,1},Array{Float64,1},Array{Float64,1}}, ::Array{Float64,1}, ::Array{Float64,1}) at /home/flo/.julia/packages/DIVAnd/lgTG2/src/fit.jl:1022
 [5] top-level scope at In[31]:1

There seems to be something with the function `fit` at line 1022 so if the same function `fit` gives the error with DIVAnd.fit, it is still present in DIVAnd.fithorzlen maybe?

**Comment by Alexander-Barth** [comment]
When I remove the NaN values, it seems to work for me:

```julia
using DIVAnd, DelimitedFiles
m = readdlm("divand_github_issue.txt")
sel = findall(isfinite.(m[:,3]));
lenz, dbinfo = DIVAnd.fithorzlen((m[sel,1],m[sel,2],m[sel,4]), m[sel,3], [50.,60.,70.])
extrema(m[sel,4])
# returns 
# (61.11283874511719, 61.11283874511719)
```
Note that the depth level is are constant in this dataset.

And thanks, I added a description for the `z` parameter  `DIVAnd.fithorzlen`.

**Comment by fricour** [comment]
Perfect, it now works ! The NaN values were the source of the issue then.

Thank you !

**Comment by Alexander-Barth** [comment]
Thank you for your confirmation!
