### ISSUE TITLE
divand Guide 

### ISSUE THREAD

**Issue by uganzedo** [gher-ulg/DIVAnd.jl#5]
Hi Alex;
Is there any manual (Guide) of the package divand in julia?
Thanks,

**Comment by Alexander-Barth** [comment]
Did you see the documentation?
https://gher-ulg.github.io/divand.jl/latest/

**Comment by meliezer** [comment]
I see that there's a need to append index.html:
[https://gher-ulg.github.io/DIVAnd.jl/latest/index.html
](https://gher-ulg.github.io/DIVAnd.jl/latest/index.html
)

**Comment by Alexander-Barth** [comment]
This is indeed now the right URL: https://gher-ulg.github.io/DIVAnd.jl/latest/index.html
