### ISSUE TITLE
mask in diva3d

### ISSUE THREAD

**Issue by JianghuiDu** [gher-ulg/DIVAnd.jl#51]
I was using `diva3d` to analyze lon-lat-depth data, no time dimension. I created a mask and included it  but I got the error 
```
ERROR: expecting a mask of the size (90, 45), but got a mask of the size (90, 45, 33)
```
In my analysis the size of lon, lat and depth grids are 90, 45 and 33 respectively.
I would assume that this mask should also be 3d, why would it be expecting a 2d mask?

I found out this error was sent by the following codes :
```
    mask2,pmn,xyi =
        if length(xi) == 4
            DIVAnd.domain(
                bathname,bathisglobal,xi[1],xi[2],xi[3];
                zlevel = zlevel)
        else
            DIVAnd.domain(bathname,bathisglobal,xi[1],xi[2])
        end

    # allow to the user to override the mask
    if mask == nothing
        mask = mask2
    else
        if size(mask) != size(mask2)
            error("expecting a mask of the size $(size(mask2)), " *
                  "but got a mask of the size $(size(mask))")
        end
        # use mask in the following and not mask2
    end
```
What happens ` if length(xi) == 4` makes obvious sense since the last dimension is time. What I do not understand is why in 
```
else 
DIVAnd.domain(bathname,bathisglobal,xi[1],xi[2])
```
only the first two dimensions are used to create the domain even if the domain is 3d?

**Comment by JianghuiDu** [comment]
Is it true that `diva3d` only deals with timeseries data, eith as lon-lat-depth-time or lon-lat-time? I read the code and feel lon-lat-depth is not supported. If that's the case please make it clear in the documents :).

**Comment by jmbeckers** [comment]
diva3d is 3D in space and 1 time dimension. Maybe the problem is that if you do not use time the 3D is interpreted as 2D in space and 1D in time ? Can you just try with a fourth dimension using only 1 point ?

**Comment by JianghuiDu** [comment]
That works, but it's rather complicated to setup the time dimension...
