### ISSUE TITLE
s.obsout and moddim

### ISSUE THREAD

**Issue by JianghuiDu** [gher-ulg/DIVAnd.jl#52]
In my lon-lat-depth analysis using DIVAndrun, observations between the last longitude grid 358 and the first longitude grid 2 were masked out and returned NaN residuals even by setting moddim = [360, 0, 0]. But this does not seem to affect the gridded results as I don't see any obvious discontinuity across 0. Am I missing something?
I checked the grid points around, this is not due to bathymetry masking, since the observations with NaN residuals are surrounded by grid points that are not masked.

**Comment by jmbeckers** [comment]
To exclude a possible explanation for the problem can you use alphabc=0 in the parameters and check if the problem remains ?
Thanks

**Comment by jmbeckers** [comment]
To exclude a possible explanation for the problem can you use alphabc=0 in the parameters and check if the problem remains ?
Thanks

**Comment by JianghuiDu** [comment]
I wonder if its a problem with `sparse_interp`
```
I = localize_separable_grid((eNdint.lon,eNdint.lat,eNdint.w_depth), mask3d, grid)

H, out 
```
See this plot (within the red rectangular, the others are masked because of bathymetry). Even with iscyclic = [true, false, false], the observations are still masked out. I read the code and I didn't find any mention of `moddim` there.

![Untitled](https://user-images.githubusercontent.com/31140772/70157673-42468c00-16b6-11ea-9340-7e60997fcee4.png)
= sparse_interp(mask3d, I, [true,false,false])

**Comment by jmbeckers** [comment]
I tried on a simple case

if the data point is in the domain (not taking into account periodicity) everything is ok

if the data points is out of the domain (say -10 if you define your grid between 0 and 360) then it is not taken into account.

So what is the grid definition ?

**Comment by JianghuiDu** [comment]
`lon = 2.0:4.0:358; lat = -88.0:4.0:88.0`
The lon of the data are between 358 and 360 OR between 0 and 2. My lon data are all in the range of 0~360. There's no negative numbers.
This plot is better because now I have removed bathymetry mask.
You can see the points out side `lat` range are masked which makes since but the longitude problem remains even using iscyclic=true.

![Untitled](https://user-images.githubusercontent.com/31140772/70158814-28a64400-16b8-11ea-9466-eb26d947578a.png)

**Comment by JianghuiDu** [comment]
Actually I don't think `iscyclic` work neither for lon nor for lat since if I do `[true, true, false]`, the data outside the long and lat domain are both masked.
But, if I do `[true, true, true]` then there is not such problem, which makes no sense since it has nothing to do with depth...

**Comment by JianghuiDu** [comment]
Maybe its related to `localize_separable_grid` which appears to have a strange behavior. It returns negative numbers for observations as long as only one dimension is outside the grid range. When calling `I` in `sparse_interp`, setting `iscyclic = true` only modifies one single dimension. For example, if an observation is outside lon grid but still within lat and depth grids, it got a negative `I` in all 3 dimension, and in `sparse_interp` setting lon as cyclic only modified the `I` in lat dimension, while the other two dimensions are still negative.

**Comment by Alexander-Barth** [comment]
Thanks a lot for your analysis. This is exactly the issue. I am now testing a fix for this problem.

**Comment by Alexander-Barth** [comment]
Can you try the new master branch?

**Comment by JianghuiDu** [comment]
Yes, It's fixed. Thanks!

**Comment by JianghuiDu** [comment]
A related question. Are the observations outside the grid domain used in the analysis?

**Comment by jmbeckers** [comment]
Observations outside of the grid are not used for the analysis (neither are observations that fall on land defined by the mask). What can happen is that some of the auxiliary tools doing statistics on the data might not check if the points are on the domain or not but the analysis itself excludes the points falling outside.
