### ISSUE TITLE
DIVAnd_residualobs returns residuals different from the "real" ones?

### ISSUE THREAD

**Issue by JianghuiDu** [gher-ulg/DIVAnd.jl#53]
I have a gridded data product. I did DIVAndrun on this data using the same grid as in the original product. However, when I compare the residuals returned by DIVAnd_residualobs  and the residuals calculated by differencing the analysis and the original gridded data, I find they are not the same (see the plot. They should be anti-correlated because the signs are opposite. You do see that trend but also a cloud of data, noise?, appears around 0). The residuals are small but clearly not due to rounding errors etc.. In the docs it is said the residuals are calculated by linearly interpolating the gridded analysis to the locations of observations. But since in my case the "data" and "analysis" are at exactly the same locations, I don't see why should these two methods give different results...

![Untitled](https://user-images.githubusercontent.com/31140772/70151324-bb8cb180-16ab-11ea-9c9f-93249061cf07.png)

**Comment by jmbeckers** [comment]
I tried with a 2D example. I suspect the reason for the difference is the default parameter alphabc which tries to reject the last grid points of the grid to "infinity" without actually moving the data points and you see a difference there. If you use alphabc=0 the results should be close to rounding errors.

**Comment by JianghuiDu** [comment]
The difference becomes bigger as epsilon2 becomes smaller.
![Untitled](https://user-images.githubusercontent.com/31140772/70155419-82a40b00-16b2-11ea-8c10-80b436d36b8f.png)

**Comment by jmbeckers** [comment]
With  alphabc=0 ?

**Comment by JianghuiDu** [comment]
It does remove the difference! But how does it affect the analysis?

**Comment by jmbeckers** [comment]
With your gridding of a gridded field it only modifies the analysis on the last and first grid point in each direction for small values of epsilon. These are the differences you see; the interior points should have the same residuals and analysis

**Comment by jmbeckers** [comment]
"about cyclic dimensions" Normally that direction should not be affected but to be sure for your other problem I asked you to check anyway.

**Comment by JianghuiDu** [comment]
For my other problem it doesn't work. Those observations between 358 and 2 are still masked out.

**Comment by jmbeckers** [comment]
Yes, that it was I expected (normally alphabc does not act in the periodic direction). So for the other problem we will need to have a closer look.
