### ISSUE TITLE
DIVAnd_qc doesn't work with advection constrain

### ISSUE THREAD

**Issue by JianghuiDu** [gher-ulg/DIVAnd.jl#54]
Some indexing problem with `s.yo` it would appear, which adds artificial "observations"?

**Comment by jmbeckers** [comment]
Indeed, very likely a bug in DIVAnd_qc line 39 should read

yo = s.obsconstrain.yo

**Comment by JianghuiDu** [comment]
Don't you need to change all `s.yo` to `s.obsconstrain.yo`? There is another `s.yo` at line 46.

**Comment by jmbeckers** [comment]
yes

**Comment by JianghuiDu** [comment]
Same problem with DIVAnd_cv

**Comment by jmbeckers** [comment]
yes, thanks for spotting those.
