### ISSUE TITLE
`nomissing` function

### ISSUE THREAD

**Issue by ctroupin** [gher-ulg/DIVAnd.jl#56]
In the docstring of `nomissing`:

> ```
> a = nomissing(da)
> ```
> Retun the values of the array da of type Array{Union{T,Missing},N} (potentially containing missing values) as a regular Julia array a of the same element type and checks that no missing values are present.
>```
>a = nomissing(da,value)
>```
>
> Retun the values of the array da of type Array{Union{T,Missing},N} as a regular Julia array a by replacing all missing value by value.

1. I'm not sure 'checks that no missing values are present.' is clear. Maybe we should say *return an error if the array contains at least one missing value*
2. Typo: `Retun → Return`
3. Typo: `arrays contains missing values...`
→ `array contains missing values...`
4. replacing all missing value → values

Also note that the function `coalesce` is available in `Base`, we could use it 
- remove the missing values (if there are some) or 
- turn the array of type Array{Union{T,Missing},N} into a type Array{T,N} if there are no missing value.

**Comment by Alexander-Barth** [comment]
I corrected the docs of NCDatasets, thanks! But I prefer to keep the function `nomissing` for now because it handles better the case where the data array is Float32 and the user uses a Float64 NaN.
The end-goal, is to be able to use missing everywhere (and in PyPlot in particular, https://github.com/JuliaPy/PyCall.jl/issues/616)

```
julia> nomissing([1.0f0,2.0f0,missing],NaN)
3-element Array{Float32,1}:
   1.0
   2.0
 NaN  

julia> coalesce.([1.0f0,2.0f0,missing],NaN)
3-element Array{AbstractFloat,1}:
   1.0f0
   2.0f0
 NaN    
```
