### ISSUE TITLE
fill gaps chlorophyll maps

### ISSUE THREAD

**Issue by uganzedo** [gher-ulg/DIVAnd.jl#6]
I want to use the divand package (julia) to reconstruct clouds of chlorophyll maps. I am using the divandrun command but it shows errors.
I'm using a netcdf of 10 images of chlorophyll, I am very lost

Could you help me a little?

**Comment by Alexander-Barth** [comment]
Can you share a reproducible (and minimal, i.e. remove all unrelated stuff) code which shows the error?

Thanks!
