### ISSUE TITLE
Wrong long name for lat

### ISSUE THREAD

**Issue by ax1ine** [gher-ulg/DIVAnd.jl#63]
Found a strange bug (?) in the netCDF output. For whatever reason long name for latitude is replaced with the one for longitude. Here's a part of the ncdump header output:
'variables:

	double lon(lon) (no compression);
		lon:units = degrees_east ;
		lon:standard_name = longitude ;
		lon:long_name = longitude ;

	double lat(lat) (no compression);
		lat:units = degrees_east ;
		lat:standard_name = longitude ;
		lat:long_name = longitude ;

	double depth(depth) (no compression);
		depth:units = meters ;
		depth:positive = down ;
		depth:standard_name = depth ;
		depth:long_name = depth below sea level ;
'

All the other variables are fine. Don't know when it has exactly happened (as I've updated Julia modules for a few times), but files I had produced with the same script on 28 January 2020 had no such problem. I've just updated both DIVAnd (v 2.5.1) and NCDatasets (v 0.10.1) modules but the issue remains.

Upd. I use the diva3d function to produce nc files

**Comment by jmbeckers** [comment]
yep seems like a typo (cut and paste error?) in DIVAnd_save.jl lines 165-166.

**Comment by Alexander-Barth** [comment]
Thank you Alexander for letting us know! This is indeed a typo. I will update the master branch once all tests succeed on my development branch.

**Comment by Alexander-Barth** [comment]
Fix is now merged in master. Thanks for reporting it!

**Comment by ax1ine** [comment]
Great! Thank you for the prompt fix, Alexander!
