### ISSUE TITLE
possible test failure in upcoming Julia version 1.5

### ISSUE THREAD

**Issue by rfourquet** [gher-ulg/DIVAnd.jl#65]
A PkgEval run for a [PR](https://github.com/JuliaLang/julia/pull/35078) which changes the generated numbers for `randn!` indicates that the tests of this package might fail in Julia 1.5 (and on Julia current master). Apologies if this is a false positive.
cf. https://github.com/JuliaCI/NanosoldierReports/blob/7de24e455342298cbef56826b5827f0d7640d2c1/pkgeval/by_hash/b89e35c_vs_098ef24/logs/DIVAnd/1.5.0-DEV-71a4a114c2.log

**Comment by Alexander-Barth** [comment]
Thanks  @rfourquet, for the info. I think these failing tests are due to change in the random number generator and the test against the reference value are probably just too strict.

**Comment by Alexander-Barth** [comment]
@jmbeckers can you check the errors in `test_2dvar_cv.jl` and `test_heatmap.jl` ? I guess that we can simply use a more tolerant check to the reference values (as the random number generator in julia has [changed](https://docs.julialang.org/en/v1.5-dev/NEWS/#Random-1)).

 I will track-down the warning related to deprecated functions.

**Comment by Alexander-Barth** [comment]
@jmbeckers does this look OK for you? https://github.com/gher-ulg/DIVAnd.jl/commit/5336d1e3b8ad069b972dd545e330b36a0109295e

**Comment by Alexander-Barth** [comment]
Thanks @rfourquet for your notice and for your work on https://github.com/rfourquet/StableRNGs.jl which was very useful to us to make tests with random data reproducible between julia versions.

**Comment by rfourquet** [comment]
You're welcome thanks!
