### ISSUE TITLE
interpolation across the North Pole and around 180E

### ISSUE THREAD

**Issue by ax1ine** [gher-ulg/DIVAnd.jl#66]
Cannot quite figure how to do a continuous interpolation over the North Pole area and across 180E. This grid definition works:
`Δx, Δy = 0.5, 0.5`
`lonr = -179.:Δx:180.`
`latr = 70.:Δy:89.`
But I get a discontinuity at 180E and over the Pole. Even considering a large correlation radius (I tried up to 1.000 km) seems like the analysis doesn't use observations from "the other side".

I tried using the entire grid defining is as:
`lonr = -180.:Δx:180.`
`latr = 70.:Δy:90.`
the diva3d analysis didn't raise any errors in this case but resulting nc files were empty (had just metadata).

Defining the grid as (any non integer first or last lat/lon): 
`Δx, Δy = 0.5, 0.5`
`lonr = -179.5.:Δx:180.`
`latr = 70.:Δy:89.5`
raises an exception "PosDefException: matrix is not positive definite; Cholesky factorization failed." I get the same error if try to increase the search radius over than 1.100 km.

How do I produce a continuous analysis over these regions? Does DIVAnd currently support such regions?

**Comment by jmbeckers** [comment]
Can you try the second version adding the keyword into the options (assuming you have 3dimensions)

moddim=[1,0,0]

It should make the analysis periodic in the first direction.

**Comment by ax1ine** [comment]
Thank you, Jean-Marie! 

One problem solved, the analysis is now smooth across 180E. This configuration worked:
`Δx,Δy = 0.5, 0.5` 
`lonr = -180.:Δx:180.` 
`latr = 70.:Δy:89.` 
with an addition of moddim=[1,0,0] to the diva3d parameters.

I still have the whole degree without analysis between 89-90N, though. Whenever I try to use
`latr = 70.:Δy:90.` 
I get empty resulting nc files. No exceptions are risen. Is it possible to get a bit closer to the Pole somehow? I could use finer grid (to avoid 90N) but still it seems it's not allowed to use decimal degrees to specify the first and the last coordinates.

**Comment by jmbeckers** [comment]
Good to know. I hope Alexander will chime in here. 
For longitude I thought the grid had not to include the repeated point and should be -179.5:0.5:180 but maybe that was changed

For the pole, the problem has a mathematical singularity at the pole so to some extent trouble is to be expected. I guess we will need to add some more saveguards internally on metrics.
In the meanwhile, from your comment on decimal degrees on first and last coordinates I guess you tried something like
 latr = 69.99.:Δy:89.99

What did happen? I do not see why the first and last coordinates would need to be integers.

**Comment by ax1ine** [comment]
I tried different combinations including 
`latr = 69.99.:Δy:89.99`
but all of them gave the same error: "PosDefException: matrix is not positive definite; Cholesky factorization failed." I tried different correlation radii but the error persisted. Also I tried smaller Δy (up to 0.1) still got the same exception.

**Comment by jmbeckers** [comment]
ok, I guess this is related to the fact that near the poles the grid distances are extremely small.

Maybe a dirty fix to that: for the last latitude line (points almost  "on" the pole), put the mask to land except say one out of 30 points (since anyway those points are all almost "identical").

**Comment by ax1ine** [comment]
Geat hack, thank you! I added everything to the north of 89.8N to the mask and this configuration worked just fine:
 `Δx, Δy = 0.5, 0.5`
 `lonr = -180.:Δx:180.'
 'latr = 70.:Δy:90.'

Many thanks once again, Jean-Marie!

**Comment by Alexander-Barth** [comment]
> For longitude I thought the grid had not to include the repeated point and should be -179.5:0.5:180 but maybe that was changed

Yes, this is correct. Essentially "lon[end+1]" should be the same point as lon[1].

For the pole singularity, we have the same issues (and potential solutions) than ocean models. For instance one can use a coordinate system with "poles" rotated on land. But this is not so trivial to implement.
