### ISSUE TITLE
Optional parameter  qv_flags not taken into account in `NCODV.load`

### ISSUE THREAD

**Issue by ctroupin** [gher-ulg/DIVAnd.jl#72]
I'm reading a netCDF file produced by ODV and I'm checking how many _good data_, _probably good_, ... data points we have.
```julia
@time obsval, obslon, obslat, obsdepth, obstime, obsid = NCODV.load(Float64, datafile, 
    "Water body salinity"; qv_flags = ["probably_good_value"]);
```
but the number of data points found is the same whatever the values in `qv_flags` (list of strings with the quality flags to be kept).

At the beginning of the function `NCODV.load` we have `accepted_status_flags = qv_flags`, which is used as the argument of function `flagvalues`:
```julia
accepted_status_flag_values =
            flagvalues(ncv_ancillary.attrib, accepted_status_flags)
```
but in `flag_values` function the 1st line says `accepted_status_flags = ["good_value", "probably_good_value"]`, so the argument of `NCODV.load` is not used.

Does that make sense?

**Comment by Alexander-Barth** [comment]
Good catch! I removed this line `accepted_status_flags = ["good_value", "probably_good_value"]`. Does it work now for you?

**Comment by ctroupin** [comment]
Great!
Acknowledgement to Helge for reporting the results of some tests.
