### ISSUE TITLE
diva2xml: No WMS links are created

### ISSUE THREAD

**Issue by meliezer** [gher-ulg/DIVAnd.jl#9]
Hi,
I've tested with 4 NetCDF files for having Sextant xml, but I see no WMS links.
Would it be possible to verify they have different names per season, maybe by a prefix of season name and ' - ' ?

Thanks,
Menashè

**Comment by Alexander-Barth** [comment]
Can you make the XML file available to me?

**Comment by Alexander-Barth** [comment]
Can you try the current master branch following the updated example here ?
https://github.com/gher-ulg/DIVAnd.jl/blob/master/src/SDNMetadata.jl#L657

**Comment by meliezer** [comment]
I see that you append the related WMSlayername in parenthesis. Great, thank you!

**Comment by Alexander-Barth** [comment]
You are welcome! Thank you for reporting this issue.
