### ISSUE TITLE
Bulls eye in region without data

### ISSUE THREAD

**Issue by ctroupin** [gher-ulg/DIVAnd.jl#90]
Opening the issue from an email received on December 4:
> I'm running into a very weird issue. My plot based on DIVA gridding has a
bulls eye that can not be traced to my data. Please see attached for my
plot based on DIVAnd.jl. The bulls eye is located around Longitude: 135oW
and Latitude 45oN. I extracted the original cruise data in the region
between Longitude of -140 and -120 and latitude of 38 and 52, but could not
find any low values that could have caused this bullseye. The same thing is
occurring on several of my plots (other variables)

**Comment by AlexElmsley** [comment]
There are some strong gradients in the data and the low values just might be due to these gradients reflected in the analysis (undershooting where you have a strong gradient). 

Also note that if you are doing 3D analyses, values from deeper or uppers layers might have some influence. 

Are there no data at all below 250 in your data set ?

**Comment by ctroupin** [comment]
I forgot to send the 2nd email:
> I did notice that if I increase the correlation length, the situation will get slightly better. My guess is that the bullseyes are not caused by some actual low values in that spot. Instead, they are caused by:
(a) a lack of data in the spot, and 
(b) a nearby trend of decreasing value towards that spot.
Under this situation, the system would automatically extrapolate to this data sparse spot and give it a low value. 

So yes, probably due to strong gradients + lack of data. 
We can suggest to change the analysis parameters, but this will only dilute the problem... 

Or create a specific background field?

**Comment by AlexElmsley** [comment]
Or if it is clear that there are never values below a certain value apply a change of variables which ensures that.

**Comment by jmbeckers** [comment]
I close that isssue because it seems  related to the data distribution itself rather then issues with DIVAnd
